services:
  cockroach:
    image: cockroachdb/cockroach:v24.1.0
    command: start-single-node --insecure
    ports:
      - "26257:26257"   # SQL
      - "8080:8080"     # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD-SHELL", "cockroach sql --insecure -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: "20g"

  scylla:
    image: scylladb/scylla:5.4
    command: --smp 2 --overprovisioned 1
    ports:
      - "9042:9042"
      - "10000:10000"
    volumes:
      - scylla-data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SHOW VERSION' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "4g"

  backend:
    build: .
    depends_on:
      cockroach:
        condition: service_healthy
      scylla:
        condition: service_healthy
    environment:
      # service names resolve as DNS hosts on the default Docker network
      COCKROACH_URL: postgres://root@cockroach:26257/defaultdb?sslmode=disable
      SCYLLA_NODES: scylla:9042
    ports:
      - "3000:3000"   # HTTP /ready
      - "50051:50051" # gRPC

volumes:
  cockroach-data:
  scylla-data:


# version: "3.9"

# services:
#   cockroach:
#     image: cockroachdb/cockroach:v24.1.0
#     command: start-single-node --insecure
#     ports:
#       - "26257:26257"   # SQL
#       - "8080:8080"     # Admin UI
#     volumes:
#       - cockroach-data:/cockroach/cockroach-data
#     deploy:
#       resources:
#         limits:
#           cpus: "8.0"    # 8 vCPUs
#           memory: "20g"  # 20 GiB RAM

#   scylla:
#     image: scylladb/scylla:5.4
#     command: --smp 2 --overprovisioned 1
#     ports:
#       - "9042:9042"     # CQL
#       - "10000:10000"   # Alternator (optional)
#     volumes:
#       - scylla-data:/var/lib/scylla
#     deploy:
#       resources:
#         limits:
#           cpus: "2.0"    # 2 vCPUs
#           memory: "4g"   # 4 GiB RAM

# volumes:
#   cockroach-data:
#   scylla-data:
